### ISSUE TITLE
Double description className

### ISSUE THREAD

**Issue by loginsan** [jm-program/todo-template#1]
```
                <span class="description">
                  <button class="icon icon-play"></button>
                  <button class="icon icon-pause"></button>
                  12:25
                </span>
                <span class="description">created 5 minutes ago</span>
```
Второй раз имеется в виду имя класса created?

**Comment by velialiev** [comment]
А где вы нашли этот код? В мастере несколько другая верстка

**Comment by velialiev** [comment]
Да, по сравнению с master, в timer действительно description приобрел несколько иной смысл и то, что раньше было description стало title, а то, что было created - description.

Я посмотрел и понял, что связано это с тем, что в верстке с таймером у нас два одинаковых стиля для текста у надписи времени таймера и у надписи, которая показывает, как давно был создан элемент.

Из-за этого в этом варианте был выделен общий класс description, который обозначает любой текст, описывающий пункт, но отличный от заголовка (.title). Думаю, это вполне подходящее название.

<img width="344" alt="изображение" src="https://user-images.githubusercontent.com/55160134/107385706-30574900-6b04-11eb-8176-6bfc281cd1a1.png">

**Comment by velialiev** [comment]
Я ответил на поставленный вопрос? Могу закрывать issue?

**Comment by loginsan** [comment]
Вели, спасибо! Да, конечно, закрывайте. Как раз сравнивал вёрстку из разных веток, подумал что могла быть ошибка. Но, как в шутке, "это не баг, это фича".

**Comment by velialiev** [comment]
Именно так :D 

Спасибо, что решили сообщить о возможном баге 👍
